### ISSUE TITLE
src equals smallest size

### ISSUE THREAD

**Issue by max-schu** [herrstucki/responsive-loader#32]
Hi,

why is responsiveImage.src set to the smallest of all values defined in "sizes" instead of the original imagesize?

doesn't seem straight forward to me, any thought behind this?

**Comment by herrstucki** [comment]
It actually sets it to the first size defined in `sizes` (which in a srcset should be the smallest).

The original size doesn't make too much sense IMO because it's usually not the size you'd want to use on a website. Let's say your original is 4800px wide and you resize it to 200, 400 and 800 px, you'd not want the `src` to reference the 4800px image.

You also don't _have_ to use the `src` as it's returned from the loader. You can also pick any size you want from `images`. For example:

```js
const responsiveImage = require('responsive?sizes[]=100,sizes[]=200,sizes[]=300!myImage.jpg');

return <img src={responsiveImage.images[1].path} srcSet={responsiveImage.srcSet} />;
```

**Comment by max-schu** [comment]
mhm, think that depends on how you take a look at "src".
I see it as a fallback for srcset, don't want to include a polyfill for that.
so in my case, i want to use the original image size if srcset is not supported otherwise it displays the mobile 320px image on IE where srcset is not supported.
will use your alternative approach, thanks!
