### ISSUE TITLE
Injecting srcset in html

### ISSUE THREAD

**Issue by AlexOuttaspace** [herrstucki/responsive-loader#73]
Hello.
I'm trying to use responsive-loader with a html file.
My loader setup: 
```
       {
          test: /\.(png|jpg)$/,
          use: {
            loader: 'responsive-loader',
            options: {
              placeholder: true,
              sizes: [400, 600, 800, 1000, 1200],
              name: 'assets/images/[name]-[width].[hash:4].[ext]'
            }
          }
        }
```
Inside .html file:
```
<img src="${require('../../assets/images/image.png').src}" srcset="${require('../../assets/images/image.png').srcSet}"/>
```

In the output:
```
<img src="undefined" srcset="undefined"/>
```

When I omit .src or .srcSet in html and write it like this:
```
<img src="${require('../../assets/images/image.png')}"  />
```
it will return a smallest image of the set:
```
<img src="assets/images/image-400.png'  />
```

In the same time, when I require an image inside my .js file, it returns an object with all properties as it's supposed.

I read a similar issue #68 but the solution proposed there did not work for me as I am not using Vue.

**Comment by slater101** [comment]
I am doing the same thing, but I am using "file-loader" to handle basically everything which is very common. 

So just using my normal image details in the html doc makes them get parsed through the entry js file regardless causing everything to be automatically "required" in the js file.

I tried a few things to get this working, it basically generates the first file and no srcset info. Too bad it doesnt work this way, if it did, this plugin would be very usefull / very muched used.

If you could simply do:

`{
                test: /\.html$/,
                use: [
                    { loader: "file-loader",
                    options: {
                        name: "[name].[ext]"
                    }
                    },
                    { loader: "extract-loader" },
                    { loader: "html-loader",
                    options: {
                        attrs: ["img:src", "use:href"],
                        // minimize: true,
                    }
                    }
                ]
            },`

and in your main js entry file just do

`require("../index.html");`

and pass this responsive-loader in the middle some how?

Then that would be amazing. Almost all other loaders work well like this. 

Maybe there is something I am missing?

I am already using file-loader to handle the standard image files, and found that it was interfering with the following settings.

`{
                test: /\.(jpg|png|gif|svg)$/,
                use: [
                  { loader: "file-loader",
                    options: {
                      name: "images/[name].[ext]",
                    }
                  }
                ]
            },`

So I also de-activated that while trying to figure this out, but no avail.

In the end, all I could get working was the creation of the first image, it was being replaced in the html like so.

`<img src="images/8f0e757e3a40bff3fa0be54a78b1318e-630.jpg" alt="Test">`

but of course, it is not creating any srcset info because I didnt set anything in the html

This is because using things like

`${require('../../assets/images/image.png')}`

seemed to be ignored when using file-loader to handle the html file.

Seems like a near miss lol, would love to have this functional while using file-loader to handle all html files. This way you would not need to specify every image, simply set a range, include the html files as required in the js entry file and forget the rest.

If anyone knows how to get this working and I am just going in the wrong direction, a nudge would be greatly appreciated.

**Comment by slater101** [comment]
I am trying to do the same thing,
Has anyone got this working while using "file-loader" to manage the html files via the process of sending the html doc through file-loader, extract-loader and html-loader?

If so, would love to know how!

Thanks!

**Comment by AlexOuttaspace** [comment]
@slater101 
I found out that for me a problem was that I was using Handlebars templates instead of .html files. As I was not actually using a lot of hbs features, I was able to switch to using raw html and everything started to work correctly.

Here's a loader I was using (I also ran into several other bugs with it):[https://www.npmjs.com/package/handlebars-loader](handlebars-loader)
